
# Setup
title:               IndianGrocery.us
email:               deepak.bhaskaran@gmail.com
tagline:             One stop shop for all your Indian grocery needs
url:                 "suryacare.github.io/indiangrocery/" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              Deepak Bhaskaran
  url:               www.qapage.com
  email:             deepak.bhaskaran@gmail.com

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: suryacare
twitter_username: 
instagram_username: 
facebook: 
linkedin_username: deepakbhaskaran
dribbble_username: 

# Custom vars
version:             1.0.1
github:
  repo:              https://github.com/kevit/devaid-jekyll-theme

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty
